### ISSUE TITLE
Content update

### ISSUE THREAD

**Issue by PhictionalOne** [fsi-tue/anfiheft#20]
**This Thread should be seen as one where the actual Issues grow out of**

It is that time of the year again. Check if content is still up to date and modify existing texts to fit the situation.

Stuff to do (feel free to append the list):
- [x] information page on *How to Corona* (not the beer)
- [x] (Corona disclaimer onto sections like *Mensen*)
  - Could be an `\newcommand{\codisc}{...}`
- [x] Take out or rewrite Sections that can definately not happen due to covid
  - Unikino,...
- [x] check if Mailing-Addresses are up to date
  - FSen und Sekretariate
- [x] (set [KKI](#18) active) <-- lacks of content right now...

**Deadline for the anfiheft ist the 30th of September**

**Comment by meret204** [comment]
**Final update/ typo fixes Info-Heft**

- [ ] fachschaft.tex/Wer ist die Fachschaft? --> "Zusammenschluss aller Studierende**n**"
- [ ] studienplaene/informatik.tex/5. Smester --> "Scherpunk**t**" and delete multicolumn
- [ ] vorlesungsfreie-zeit/klausuren.tex/corona disclaimer --> (**r**echtzeitig heißt ein Monat)**.**
- [ ] vorlesungsfreie-zeit/praktika.tex --> "Ihr solltet daher im **Laufe**..."
- [ ] uni/gebaude.tex/ttr --> "...Computergraphik sucht **,** wird..."
- [ ] uni/infrastruktur.tex/Studierendenterminals --> ".. in der Nähe der **Damentoilette**,..."
- [ ] uni/infrastruktur.tex/Prüfungssekretariate --> "...Gründen über **Alma**..."
- [ ] infra/zdv.tex/EMail --> ".. an der Uni als auch **Z**uhause..."
- [ ] infra/zdv.tex/Pools --> "...Gebäude**ö**ffnungszeiten."
- [ ] infra/verkehr.tex/Mit dem Bus --> "..großen Bescheinigungsbogens mitbringen, der euch nach der Einschreibung per Post.." ist das nicht inzwischen alles online bei Alma?
- [ ] infra/verkehr.tex/Mit dem Bus --> "..unter der Woche ab 19 Uhr und am Wochenende **und Feiertagen** ganztägig..."
- [ ] tuebingen/sehenswuerdigkeiten.tex/Stocherkähne --> "...und es sich zutraut**,** kann.."
- [ ] tuebingen/freizeitgestaltung.tex/Kino --> **vier** Kinos (Arsenal, Atelier, Museum, Blaue Brücke) und die Hollywoodfilme werden in Museum/BB gezeigt, kleine Filme in den A-Kinos
- [ ] adressen.tex/unsere Professoren --> Kasneci neue Studiendekanin, nicht mehr Nieselt; Bringmann neuer Fachbereichssprecher, Geiger und Ostermann stv. Fachbereichssprecher
- [ ] adressen.tex/Wichtige Personen --> Tanja Krumpe löschen, Stelle gibt es nicht mehr

**Comment by meret204** [comment]
**Final update/ typo fixes Kogni-Heft**
- [ ] kogni/secondpage.tex --> update "Redaktion"
- [ ] kogni/fachschaft.tex/Wie kann ich mitmachen?/ Corona Disclaimer --> "...Hygienevorschriften..." and "...online per Zoom-**M**eeting..."
- [ ] kogni/erste_woche/was-erwartet-euch.tex --> "**Wir möchten euch außerdem** noch ein paar Infos zu den.."; delete first part of sentence
- [ ] kogni/erste_woche/was-erwartet-euch.tex/Informatik 1 --> "...welche ihr dann in den Übungen **Z**uhause.."
- [ ] kogni/erste_woche/zukunft.tex --> "Die Module, die ohne **Mehraufwand a**nrechenbar sind..."
- [ ] kogni/vorlesungsfreie-zeit/klausuren.tex/ Corona Disclaimer --> "...wird dann in den einzelnen Veranstaltungen besprochen. **Es ist jedoch wahrscheinlich, dass einige Prüfungen nicht wie sonst in präsenz, sondern online stattfinden.**; delete last sentence
- [ ] kogni/uni/infrastruktur.tex/Studierendenterminals --> ".. in der Nähe der Damentoilette,..."
- [ ]  kogni/uni/infrastruktur.tex/Bibliotheken/Fachschaftsbibliothek --> ..."interessante **Allgemeinliteratur**"
- [ ] kogni/hilfe/hilfe.tex/Corona Disclaimer--> delete disclaimer, no restrictions of the offers due to corona!
- [ ] kogni/hilfe/hilfe.tex/Studienfachberatung --> "...gestellt. **Neben der Beschreibung eures Anliegens solltet ihr euren Studiengang, Semester und Matrikelnummer angeben.** Termi**e** ..."
- [ ] kogni/hilfe/hilfe.tex/Koordination und Lehre --> replace URL with https://uni-tuebingen.de/de/135985
- [ ] kogni/hilfe/mailinglisten.tex --> delete "(Teilnahme an Versuchen)" behind sport@.. and info-jobs@..
- [ ] kogni/hilfe/mailinglisten.tex/sport@... --> paragraph behind "...anmelden."
- [ ] kogni/anhang/langeplaene --> update uebersicht_sand.pdf
- [ ] kogni/adressen.tex/Unsere Professoren --> "Eine Liste aller **p**rüfungsberechtigten Personen..."
